accounts/urls.py
from django.urls import path

from accounts.views import index, StaffDetailsView

urlpatterns = [
    path("", index, name="index"),
    path("<int:pk>/", StaffDetailsView.as_view(), name="staff-detail"),
]

app_name = "accounts"

menu/urls.py
from django.urls import path

from menu import views

urlpatterns = [
    path("", views.MenuIndexView.as_view(), name="index"),
    path("create/", views.menu_create, name="menu-create"),
    path("update/<int:pk>", views.menu_update, name="menu-update"),
    path("delete/<int:pk>", views.menu_delete, name="menu-delete"),
    path("menu-items/", views.MenuItemListView.as_view(), name="item-index"),
    path("menu-items/create/", views.menu_item_create, name="item-create"),
    path("menu-items/<int:pk>", views.menu_item_details, name="item-detail"),
    path("menu-items/update-item/<int:pk>", views.menu_item_update, name="item-update"),
    path("menu-items/delete-item/<int:pk>", views.menu_item_try_delete, name="item-delete"),
    path("menu-items/confirm-delete-item/<int:pk>", views.menu_item_confirm_delete, name="item-confirm-delete-in-menu"),
]

app_name = "menus"

table_desk_pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from table_desk_pos.views import index

urlpatterns = [
  path("admin/", admin.site.urls),
  path("accounts/", include("django.contrib.auth.urls")),
  path("", index, name="index"),
  path("menus/", include("menu.urls", namespace="menus")),
  path("orders/", include("ordering.urls", namespace="orders")),
  path("point-of-sale/", include("point_of_sale.urls", namespace="point_of_sale")),
  path("staff/", include("accounts.urls", namespace="accounts")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
<footer class="bg-dark text-light py-2 mt-auto">
  <div class="container-fluid">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-center">
      <div class="mb-2 mb-md-0">
        &copy; {% now "Y" %} Vitalii Prushak
      </div>
      <div>
        <a href="https://github.com/gheifr" class="text-light me-3" target="_blank" rel="noopener">
          <i class="bi bi-github"></i></a>
        <a href="https://wa.me/380634790828" class="text-light me-3" target="_blank" rel="noopener">
          <i class="bi bi-whatsapp"></i></a>
        <a href="mailto:v.prushak@gmail.com" class="text-light">
          <i class="bi bi-envelope"></i>
        </a>
      </div>
    </div>
  </div>
</footer>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">TableDesk</a>

    <button class="navbar-toggler" type="button"
            data-bs-toggle="collapse" data-bs-target="#mainNavbar"
            aria-controls="mainNavbar" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="mainNavbar">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'orders:index' %}">Orders</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'menus:index' %}">Menus</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'menus:item-index' %}">Menu Items</a>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link active"
                                  href="{% url 'accounts:staff-detail' user.id %}">Hi, {{ user.first_name }} {{ user.last_name }}</a>
          </li>
          {% if user.is_superuser %}
            <li class="nav-item"><a class="nav-link active"
                                  href="{% url 'admin:index' %}">Control panel</a>
          </li>
          {% endif %}
          <li class="nav-item">
            {% include 'registration/logout.html' %}
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'login' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% if is_paginated %}
  <div class="d-flex justify-content-center my-3 fixed-bottom-30">
    <div class="btn-group" role="group" aria-label="Pagination">

      <a
          class="btn btn-sm btn-outline-dark {% if not page_obj.has_previous %}disabled{% endif %}"
          href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}"
      >
        ← Prev
      </a>

      <span class="btn btn-sm btn-outline-dark active">
        {{ page_obj.number }} of {{ paginator.num_pages }}
      </span>

      <a
          class="btn btn-sm btn-outline-dark {% if not page_obj.has_next %}disabled{% endif %}"
          href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}"
      >
        Next →
      </a>

    </div>
  </div>
{% endif %}