menu/urls.py
from django.urls import path

from menu import views

urlpatterns = [
    path("", views.MenuIndexView.as_view(), name="index"),
    path("create/", views.menu_create, name="menu-create"),
    path("update/<int:pk>", views.menu_update, name="menu-update"),
    path("delete/<int:pk>", views.menu_delete, name="menu-delete"),
    path("menu-items/", views.MenuItemListView.as_view(), name="item-index"),
    path("menu-items/create/", views.menu_item_create, name="item-create"),
    path("menu-items/<int:pk>", views.menu_item_details, name="item-detail"),
    path("menu-items/update-item/<int:pk>", views.menu_item_update, name="item-update"),
    path("menu-items/delete-item/<int:pk>", views.menu_item_try_delete, name="item-delete"),
    path("menu-items/confirm-delete-item/<int:pk>", views.menu_item_confirm_delete, name="item-confirm-delete-in-menu"),
]

app_name = "menus"

table_desk_pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from table_desk_pos.views import index

urlpatterns = [
  path("admin/", admin.site.urls),
  path("accounts/", include("django.contrib.auth.urls")),
  path("", index, name="index"),
  path("menus/", include("menu.urls", namespace="menus")),
  path("orders/", include("ordering.urls", namespace="orders")),
  path("point-of-sale/", include("point_of_sale.urls", namespace="point_of_sale")),
  path("staff/", include("accounts.urls", namespace="accounts")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

menu/models.py
from django.db import models

from point_of_sale.models import Property


class Menu(models.Model):
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)

    properties = models.ManyToManyField(
        "point_of_sale.Property",
        related_name="menus",
        blank=True,
    )

    def __str__(self):
        return self.name


class MenuItem(models.Model):
    name = models.CharField(max_length=255)
    menu_section = models.CharField(max_length=50)  # 'meat', 'fish', 'kids', etc.
    price = models.DecimalField(max_digits=8, decimal_places=2)
    is_active = models.BooleanField(default=True)

    menus = models.ManyToManyField(
        Menu,
        related_name="items",
        blank=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]

menu/forms.py
from django import forms

from menu.models import MenuItem, Menu


class MenuForm(forms.ModelForm):
    items = forms.ModelMultipleChoiceField(
        queryset=MenuItem.objects.filter(is_active=True),
        required=False,
        widget=forms.CheckboxSelectMultiple(attrs={"class": "form-check-inline-dark"}),
        label="Menu items",
    )
    menu_sections = []

    class Meta:
        model = Menu
        fields = ("name", "is_active", "properties", "items")
        widgets = {
            "is_active": forms.CheckboxInput(attrs={"class": "form-check-inline-dark"}),
            "properties": forms.CheckboxSelectMultiple(attrs={"class": "form-check-inline-dark"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.menu_sections = sorted(set(mi.menu_section.title() for mi in MenuItem.objects.filter(is_active=True)))
        if self.instance.pk:
            self.fields["items"].initial = self.instance.items.all()

    def save(self, commit=True):
        menu = super().save(commit=commit)

        def save_m2m():
            menu.items.set(self.cleaned_data["items"])

        if commit:
            save_m2m()
        else:
            self.save_m2m = save_m2m

        return menu


class MenuItemForm(forms.ModelForm):
    class Meta:
        model = MenuItem
        fields = ["name", "menu_section", "is_active", "price", "menus"]
        widgets = {
            "is_active": forms.CheckboxInput(attrs={"class": "form-check-inline-dark"}),
            "menus": forms.CheckboxSelectMultiple(attrs={
                "class": "form-check-inline-dark"}),
            "price": forms.NumberInput(attrs={"min": 0, "value": 0}),
        }


class MenuItemSearchForm(forms.Form):
    search_field_menu_item = forms.CharField(
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}, ),
    )

menu/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.shortcuts import redirect, get_object_or_404, render
from django.views import generic

from menu.forms import MenuItemForm, MenuItemSearchForm, MenuForm
from menu.models import MenuItem, Menu


class MenuIndexView(LoginRequiredMixin, generic.ListView):
    model = MenuItem
    template_name = "menu/index.html"
    context_object_name = "items"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        menus = (
            Menu.objects
            .filter(is_active=True, items__isnull=False)
            .prefetch_related("items")
            .order_by("name")
            .distinct()
        )
        context["menus"] = menus

        menu_id = self.request.GET.get("menu")
        active_menu = None
        if menu_id:
            active_menu = menus.filter(pk=menu_id).first()
        if not active_menu and menus.exists():
            active_menu = menus.first()
        context["active_menu"] = active_menu

        sections = []
        items_by_section = {}

        if active_menu:
            items = (
                MenuItem.objects.filter(is_active=True, menus=active_menu)
                .order_by("menu_section", "name")
            )
            for item in items:
                sec = item.menu_section or "Other"
                if sec not in items_by_section:
                    items_by_section[sec] = []
                    sections.append(sec)
                items_by_section[sec].append(item)

        context["sections"] = sections
        context["items_by_section"] = items_by_section
        return context


@login_required()
def menu_create(request):
    if request.method == "POST":
        form = MenuForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("menus:index")

    form = MenuForm()
    items_qs = form.fields["items"].queryset
    item_widgets = list(form["items"])
    items_with_widgets = list(zip(items_qs, item_widgets))

    context = {
        "form": form,
        "items_with_widgets": items_with_widgets,
    }
    return render(
        request,
        "menu/menu_form.html",
        context,
    )


@login_required()
def menu_update(request, pk):
    menu = get_object_or_404(Menu.objects.all(), pk=pk)

    if request.method == "POST":
        menu_form = MenuForm(request.POST, instance=menu)
        if menu_form.is_valid():
            with transaction.atomic():
                all_items = menu_form.cleaned_data["items"]
                menu = menu_form.save(commit=False)
                menu.items.set(all_items)

                menu.save()
            return redirect("menus:index")

    menu_form = MenuForm(instance=menu)
    items_qs = menu_form.fields["items"].queryset
    item_widgets = list(menu_form["items"])
    items_with_widgets = list(zip(items_qs, item_widgets))
    context = {
        "menu": menu,
        "form": menu_form,
        "items_with_widgets": items_with_widgets,
    }
    return render(
        request,
        "menu/menu_form.html",
        context,
    )


@login_required()
def menu_delete(request, pk):
    menu = get_object_or_404(Menu.objects.all(), pk=pk)
    if request.method == "POST":
        menu.delete()
        return redirect("menus:index")

    return render(
        request,
        "menu/menu_confirm_delete.html",
        {
            "menu": menu},
    )


@login_required
def menu_item_details(request, pk):
    return redirect("menus:item-update", pk=pk)


class MenuItemListView(LoginRequiredMixin, generic.ListView):
    model = MenuItem
    paginate_by = 10
    template_name = "menu/menuitem_list.html"

    def get_context_data(self, **kwargs):
        context = super(MenuItemListView, self).get_context_data(**kwargs)
        search_field_menu_item = self.request.GET.get(
            "search_field_menu_item",
            ""
        )
        context["search_field_menu_item"] = search_field_menu_item
        context["search_form"] = MenuItemSearchForm(
            initial={"search_field_menu_item": search_field_menu_item}
        )
        return context

    def get_queryset(self):
        queryset = MenuItem.objects.prefetch_related("menus")
        form = MenuItemSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["search_field_menu_item"]
            )
        return queryset


@login_required()
def menu_item_update(request, pk):
    menu_item = get_object_or_404(
        MenuItem.objects.prefetch_related("menus"),
        pk=pk
    )
    if request.method == "POST":
        form = MenuItemForm(request.POST, instance=menu_item)

        if form.is_valid():
            with transaction.atomic():
                form.save()

                for menu in menu_item.menus.all():

                    mi = menu.items

                    if not menu_item in menu.items.all():
                        menu.items.add(menu_item)

        return redirect("menus:item-index")
    else:
        form = MenuItemForm(instance=menu_item)

    return render(
        request,
        "menu/menuitem_form.html",
        {
            "menu_item": menu_item,
            "form": form,
        },
    )


@login_required()
def menu_item_create(request):
    if request.method == "POST":
        form = MenuItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("menus:item-index")
        else:
            return render(
                request,
                "menu/menuitem_form.html",
                {"form": form},
            )

    else:
        form = MenuItemForm()
        return render(
            request,
            "menu/menuitem_form.html",
            {"form": form},
        )


@login_required()
def menu_item_try_delete(request, pk):
    menu_item = get_object_or_404(MenuItem.objects.all(), pk=pk)

    if request.method == "GET":
        return render(
            request,
            'menu/menuitem_confirm_delete.html',
            {
                "menuitem": menu_item,
            },
        )
    else:
        if menu_item.menus.all().count() > 0:
            return redirect("menus:item-confirm-delete-in-menu", pk=menu_item.pk)
        else:
            menu_item.delete()
        return redirect("menus:item-index")


@login_required()
def menu_item_confirm_delete(request, pk):
    menu_item = get_object_or_404(MenuItem.objects.all(), pk=pk)

    if request.method == "GET":
        return render(
            request,
            "menu/menuitem_confirm_delete_in_menu.html",
            {"menuitem": menu_item},
        )
    else:
        for menu in menu_item.menus.all():
            menu_item.menus.remove(menu)

        menu_item.delete()

    return redirect("menus:item-index")

templates/menu/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  <title>Menu · TableDesk POS</title>
{% endblock %}

{% block content %}
  <section class="py-4"
           style="background-image: url('{% static "img/pages-background-papyrus-cold.png" %}'); padding-bottom: 10px">

    <div class="col-12">
      <div class="row">
        {# Left navigation column #}
        <aside class="col-12 col-md-3 col-lg-2 mb-3 sticky-menu-section">
          <div class="mb-4">
            <h5 class="mb-2">Menus</h5>
            <ul class="list-group">
              {% for menu in menus %}
                <li class="list-group-item p-1">
                  <a href="{% url 'menus:index' %}?menu={{ menu.id }}"
                     class="{% if active_menu and active_menu.id == menu.id %}fw-bold{% endif %} link-body-emphasis link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover">
                    {{ menu.name }}
                  </a>
                </li>
              {% empty %}
                <li class="list-group-item">No menus defined.</li>
              {% endfor %}
            </ul>
          </div>

          <div>
            <h5 class="mb-2">Sections</h5>
            <ul class="list-group">
              {% for section in sections %}
                <li class="list-group-item p-1">
                  <a href="#{{ section }}"
                     class="link-body-emphasis link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover">{{ section|title }}</a>
                </li>
              {% empty %}
                <li class="list-group-item">No sections.</li>
              {% endfor %}
            </ul>
          </div>
        </aside>

        {# Right main #}
        <section class="col-12 col-md-9 col-lg-10 main-menu-display-section">
          {% if active_menu %}
            <div class="row align-items-center justify-content-between">
              <div class="col-9">
                <h2 class="mb-3">{{ active_menu.name }}</h2>
              </div>
              <div class="col-3 d-flex justify-content-end">
                <a href="{% url 'menus:menu-update' active_menu.pk %}" class="btn btn-outline-dark m-1">
                  Edit
                </a>
                <a href="{% url 'menus:menu-create' %}" class="btn btn-outline-dark m-1">
                  New
                </a>
              </div>
            </div>

            {% if items_by_section %}
              {% for section, items in items_by_section.items %}
                <h4 class="mt-3 mb-2" id="{{ section }}">
                  {{ section|title }}
                </h4>
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-3">
                  {% for item in items %}
                    <div class="col">
                      <div class="card h-100">
                        <div class="card-body">
                          <h5 class="card-title">{{ item.name }}</h5>
                          <p class="card-text mb-1">
                            {{ item.price }} ₴
                          </p>
                          <p class="card-text">
                            <small class="text-muted">{{ item.section }}</small>
                          </p>
                        </div>
                      </div>
                    </div>
                  {% endfor %}
                </div>
              {% endfor %}
            {% else %}
              <p>No items in this menu yet.</p>
            {% endif %}
          {% else %}
            <p>Select a menu from the list on the left.</p>
          {% endif %}
        </section>
      </div>
    </div>
  </section>
{% endblock %}

templates/menu/menu_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% block content %}
  <section class="py-4 mx-0 d-flex align-items-center"
           style="background-image: url('{% static "img/pages-background-papyrus-cold.png" %}')">
    <div class="container">
      <div class="row ">
        <div class="col-12 d-flex align-items-center justify-content-center">
          <h1>Confirm Menu Delete</h1>
        </div>
      </div>
      <div class="row">
        <div class="col d-flex align-items-center justify-content-center">
          <h3>Menu: <span class="text-danger">{{ menu.name }}</span>,
            contains
            {% if menu.items.count > 0 %}
              {{ menu.items.count }} item{{ menu.items.count|pluralize }}.
            {% else %}
              no items.
            {% endif %}
          </h3>
        </div>
      </div>
      <form action="" method="post">
        {% csrf_token %}
        <div class="row d-flex align-items-center justify-content-center mt-5">
          <div class="col-6 d-flex justify-content-between">
            <input type="submit" value="Delete" class="btn btn-outline-danger"
                   style="min-width: 100px">
            <button type="button"
                    class="btn btn-outline-dark "
                    style="min-width: 100px"
                    onclick="history.back()">
              Cancel
            </button>
          </div>
        </div>
      </form>
    </div>
  </section>
{% endblock %}

templates/menu/menu_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}
  <section class="py-4"
           style="background-image: url('{% static "img/pages-background-papyrus-cold.png" %}'); padding-bottom: 10px">
    <div class="container-fluid">
      <div class="row justify-content-between">
        <div class="col-6">
          <h2>
            {% if menu.pk %}{{ menu.name }}{% else %}New Menu{% endif %}
          </h2>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
          {% if menu.pk %}
            <a href="{% url 'menus:menu-delete' menu.pk %}" class="btn btn-outline-dark bg-danger-subtle">
              Delete
            </a>
          {% endif %}
        </div>
        <hr>
      </div>
    </div>

    <form action="" method="post">
      {% csrf_token %}
      <div class="card pb-3">
        <div class="card-body">
          <div class="row mb-1 d-flex justify-content-end align-items-center">
            <div class="col-2">
              <strong>Name:</strong>
            </div>
            <div class="col ">
              {{ form.name }}
            </div>
          </div>

          <div class="row mb-1 d-flex justify-content-end align-items-center">
            <div class="col-2">
              <label for="g_qty{{ order.id }}">
                <strong>Properties</strong>
              </label>
            </div>
            <div class="col ">
              {{ form.properties }}
            </div>
          </div>

          <div class="row mb-1 d-flex justify-content-end align-items-center">
            <div class="col-2">
              <label for="g_qty{{ order.id }}">
                <strong>Active:</strong>
              </label>
            </div>
            <div class="col ">
              {{ form.is_active }}
            </div>
          </div>
          <hr>
          <div class="row mb-1 d-flex justify-content-end align-items-center">
            <div class="row">
              <div class="col-2 mb-2">
                <label>
                  <strong>Menu Items:</strong>
                </label>
              </div>
            </div>
            <div class="col">
              {% if form.items %}
                <nav>
                  <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    {% for sec in form.menu_sections %}
                      <button class="nav-link {% if forloop.first %}active{% endif %}"
                              id="nav-{{ sec|slugify }}-tab"
                              data-bs-toggle="tab"
                              data-bs-target="#nav-{{ sec|slugify }}"
                              type="button"
                              role="tab"
                              aria-controls="nav-{{ sec|slugify }}"
                              aria-selected="{% if forloop.first %}true{% else %}false{% endif %}">
                        {{ sec }}
                      </button>
                    {% endfor %}
                  </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                  {% for sec in form.menu_sections %}
                    <div class="tab-pane fade {% if forloop.first %} show active{% endif %}"
                         id="nav-{{ sec|slugify }}"
                         role="tabpanel"
                         aria-labelledby="nav-{{ sec|slugify }}-tab">
                      {% for menu_item, checkbox in items_with_widgets %}
                        {% if menu_item.menu_section.title == sec %}
                          <div>
                            {{ checkbox }} - {{ menu_item.price }} ₴
                          </div>
                        {% endif %}
                      {% endfor %}
                    </div>
                  {% endfor %}
                </div>
              {% else %}
                <span>No items yet</span>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-end mt-3">
        <a href="#" onclick="history.back()" class="btn btn-outline-danger me-2 ">
          Cancel
        </a>
        <button type="submit" class="btn btn-outline-dark btn-sm">
          Save changes
        </button>
      </div>
    </form>
  </section>
{% endblock %}

templates/menu/menuitem_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}
  <section class="py-4 d-flex align-items-center w-100"
           style="background-image: url('{% static "img/pages-background-papyrus-cold.png" %}')">
    <div class="container">
      <div class="row justify-content-center align-content-center">
        <div class="col-9 d-flex justify-content-center align-content-center">
          <h1>Confirm Menu Item Delete?</h1>
        </div>
      </div>

        <div class="row d-flex justify-content-center">
          <div class="col-6">
            <table class="table table-bordered border-light-subtle bg-transparent">
              <thead>
              <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Section</th>
                <th>{% if menuitem.menus.count > 1 %}Menus{% else %}Menu{% endif %}</th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td>{{ menuitem.name }}</td>
                <td>{{ menuitem.price|floatformat:2 }} ₴</td>
                <td>{{ menuitem.menu_section }}</td>
                <td>
                  {% if menuitem.menus %}
                    {% if menuitem.menus.count > 1 %}
                      {% for menu in menuitem.menus.all %}
                        {{ menu.name }}<br>
                      {% endfor %}
                    {% else %}
                      {{ menuitem.menus.first.name }}
                    {% endif %}
                  {% else %}
                    Not assigned
                  {% endif %}
                </td>
              </tr>
              </tbody>
            </table>
        </div>
      </div>

      <div class="row d-flex justify-content-center">
        <div class="col-6">
          <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="row justify-content-center align-content-center">
              <div class="col d-flex justify-content-between ">
                <input type="submit" value="Delete" class="btn btn-outline-danger"
                       style="min-width: 100px">
                <button type="button"
                        class="btn btn-outline-dark "
                        style="min-width: 100px"
                        onclick="history.back()">
                  Cancel
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/menu/menuitem_confirm_delete_in_menu.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}
  <section class="py-4 d-flex align-items-center w-100"
           style="background-image: url('{% static "img/pages-background-papyrus-cold.png" %}')">
    <div class="container">
      <div class="row justify-content-center align-content-center">
        <div class="col-9 ">
          <h1 class="">
            This Menu Item is assigned to <strong> {{ menuitem.menus.all.count }}
              menu{{ menuitem.menus.all.count|pluralize }}.</strong>
            <br>
          </h1>
          <h3>
            In case you proceed, item will be removed from
            {% if menuitem.menus.all.count > 1 %}
              all menus
            {% else %}
              the menu
            {% endif %}
          .
          </h3>
        </div>
      </div>

      <div class="container">
        <div class="row d-flex justify-content-center">
          <div class="col-8">
            <table class="table table-bordered border-light-subtle bg-transparent">
              <thead>
              <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Section</th>
                <th>{% if menuitem.menus.count > 1 %}Menus{% else %}Menu{% endif %}</th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td>{{ menuitem.name }}</td>
                <td>{{ menuitem.price|floatformat:2 }} ₴</td>
                <td>{{ menuitem.menu_section }}</td>
                <td>
                  {% if menuitem.menus %}
                    {% if menuitem.menus.count > 1 %}
                      {% for menu in menuitem.menus.all %}
                        {{ menu.name }}<br>
                      {% endfor %}
                    {% else %}
                      {{ menuitem.menus.first.name }}
                    {% endif %}
                  {% else %}
                    Not assigned
                  {% endif %}
                </td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="row justify-content-center">
        <div class="col-9 ">
          <form action="" method="post">
            {% csrf_token %}
            <div class="row">
              <div class="col d-flex justify-content-between ">
                <input type="submit" value="Delete" class="btn btn-outline-danger" style="min-width: 100px">
                <a class="btn btn-outline-dark "
                   style="min-width: 100px"
                   href="{% url 'menus:item-index' %}">
                  Cancel
                </a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/menu/menuitem_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="py-4 mx-0 align-items-center"
           style="background-image: url('{% static "img/pages-background-papyrus-cold.png" %}')">
    <h2>{{ menuitem.name }}</h2>
    <hr>

  </section>
{% endblock %}

templates/menu/menuitem_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}
  <section class="py-4 mx-0 align-items-center"
           style="background-image: url('{% static "img/pages-background-papyrus-cold.png" %}')">
    <div class="col-12 col-lg-8 offset-lg-2 mt-3">
      <div class="row">
        <div class="col-8">
          <h2>
            {% if menu_item.pk %}{{ menu_item.name }}{% else %}New Item{% endif %}
          </h2>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
          {% if menu_item.pk %}
            <a href="{% url 'menus:item-delete' menu_item.pk %}" class="btn btn-outline-dark bg-danger-subtle">
              Delete
            </a>
          {% endif %}
        </div>
        <br>
        <form action="" method="post">
          {% csrf_token %}
          <div class="card pb-3">
            <div class="card-body">
              <div class="row mb-1 d-flex justify-content-end align-items-center">
                <div class="col-2">
                  <strong>Name:</strong>
                </div>
                <div class="col ">
                  {{ form.name }}
                </div>
              </div>

              <div class="row mb-1 d-flex justify-content-end align-items-center">
                <div class="col-2">
                  <label for="g_qty{{ order.id }}">
                    <strong>Price, ₴:</strong>
                  </label>
                </div>
                <div class="col">
                  {{ form.price }}
                </div>
              </div>

              <div class="row mb-1 d-flex justify-content-end align-items-center">
                <div class="col-2">
                  <label for="g_qty{{ order.id }}">
                    <strong>Menu Section:</strong>
                  </label>
                </div>
                <div class="col ">
                  {{ form.menu_section }}
                </div>
              </div>

              <div class="row mb-1 d-flex justify-content-end align-items-center">
                <div class="col-2">
                  <label for="g_qty{{ order.id }}">
                    <strong>Active:</strong>
                  </label>
                </div>
                <div class="col ">
                  {{ form.is_active }}
                </div>
              </div>
              <hr>
              <div class="row mb-1 d-flex justify-content-end align-items-center">
                <div class="col-2">
                  <label for="g_qty{{ order.id }}">
                    <strong>Menus:</strong>
                  </label>
                </div>
                <div class="col ">
                  {{ form.menus }}
                </div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-end mt-3">
            <a href="#" onclick="history.back()" class="btn btn-outline-danger me-2 ">
              Cancel
            </a>
            <button type="submit" class="btn btn-outline-dark btn-sm">
              Save changes
            </button>
          </div>
        </form>
      </div>
    </div>
  </section>
{% endblock %}

templates/menu/menuitem_list.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}
  <section class="py-4 mx-0 align-items-center"
           style="background-image: url('{% static "img/pages-background-papyrus-cold.png" %}')">
    <div class="row justify-content-between">
      <div class="col-3">
        <h2>Menu Items</h2>
      </div>
      <div class="col-3 d-flex justify-content-end align-items-center">
        <a class="btn btn-outline-dark"
           href="{% url 'menus:item-create' %}">
          Create new
        </a>
      </div>
    </div>
    {#  Search form #}
    <form action="" method="get">
      <div class="col d-flex align-items-center justify-content-start">
        <div class="p-1">{{ search_form }}</div>
        <input type="submit" value="🔎" class="btn btn-outline-secondary btn-sm">
      </div>
    </form>
    {% if menuitem_list %}
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Name</th>
          <th>Menu section</th>
          <th>Price</th>
          <th>Menu(s)</th>
        </tr>
        </thead>
        <tbody>
        {% for item in menuitem_list %}
          <tr class="clickable-row" data-href="{% url 'menus:item-detail' item.id %}">
            <td class="w-25">{{ item.name }}</td>
            <td class="w-25">{{ item.menu_section }}</td>
            <td class="w-25">{{ item.price|floatformat:2 }} ₴</td>
            <td class="w-25">
              {% if item.menus.count > 1 %}
                {% for menu in item.menus.all %}
                  → {{ menu.name }}<br>
                {% endfor %}
              {% else %}
                {{ item.menus.first.name }}
              {% endif %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    {% else %}
      No items
    {% endif %}
    {% include "includes/pagination.html" %}
  </section>
{% endblock %}